### PR TITLE
WL-3835: Change to the help from changes to the Add Assignments form

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-assignment/pull/15

**Comment by buckett** [comment]
Not doing the images?

**Comment by nicholaswilson100** [comment]
Ah yes forgotten about those...

**Comment by nicholaswilson100** [comment]
For updated images,

https://github.com/ox-it/wl-reference/pull/71

**Pull request merged**
